name: quickbrain
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy>=1.24
  - nibabel>=5.0
  - scipy>=1.11
  - matplotlib>=3.7
  - pytest>=8.0
  - scipy>=1.11
  - matplotlib>=3.7
  - ipykernel
  - brainchop=0.2.5
  - pip
  - pip:
      - torch
      - torchvision
      - scikit-image==0.26.0
      - -e .
